import { useEffect, useMemo, useState } from 'react'
import { Home, Search, CalendarDays, UserRound, ChevronDown, Bell, Menu, Sparkles, CheckCircle2, X } from 'lucide-react'
import { providers as seedProviders, seedBookings } from '../data/seed'
import { Modal } from '../components/Modal'
import { App as CapacitorApp } from '@capacitor/app'
import { useAndroidBack } from '../navigation/useAndroidBack'
import { HomeView, SearchView, BookingsView, ProfileView, ProviderDashboard, AdminView, HelpView, FeedbackView, ProviderForm } from '../features/pages/Pages'
import { ProviderDetails, BookingFlow, BookingDetails, ReviewForm, FilterPanel } from '../features/pages/Dialogs'
const safeStored=(key,fallback)=>{try{const value=localStorage.getItem(key);return value?JSON.parse(value):fallback}catch{return fallback}}
const makeProviderForm=()=>({name:'',role:'',category:'Plumbing',price:'',location:'Colombo 04',description:''})
export default function App(){
 const[view,setView]=useState('home'),[role,setRole]=useState('customer'),[providers,setProviders]=useState(()=>safeStored('hs-providers',seedProviders)),[bookings,setBookings]=useState(()=>safeStored('hs-bookings',seedBookings)),[reviews,setReviews]=useState(()=>safeStored('hs-reviews',[])),[query,setQuery]=useState(''),[category,setCategory]=useState('All services'),[sort,setSort]=useState('Recommended'),[filterOpen,setFilterOpen]=useState(false),[maxPrice,setMaxPrice]=useState(5000),[minRating,setMinRating]=useState(0),[selected,setSelected]=useState(null),[bookingProvider,setBookingProvider]=useState(null),[toast,setToast]=useState(''),[menuOpen,setMenuOpen]=useState(false),[activeTab,setActiveTab]=useState('Upcoming'),[date,setDate]=useState('2026-10-10'),[time,setTime]=useState('10:00 AM'),[address,setAddress]=useState('No. 32, Kotte Road, Colombo 04'),[bookingStage,setBookingStage]=useState('details'),[paymentMethod,setPaymentMethod]=useState('Cash on Delivery'),[manageProvider,setManageProvider]=useState(null),[form,setForm]=useState(makeProviderForm),[reviewBooking,setReviewBooking]=useState(null),[rating,setRating]=useState(5),[reviewText,setReviewText]=useState(''),[profileName,setProfileName]=useState('Amaya Perera'),[profileLocation,setProfileLocation]=useState('Colombo 04')
 useAndroidBack(() => {
  if (selected) setSelected(null)
  else if (bookingProvider) setBookingProvider(null)
  else if (filterOpen) setFilterOpen(false)
  else if (reviewBooking) setReviewBooking(null)
  else if (manageProvider === 'new') setManageProvider(null)
  else if (menuOpen) setMenuOpen(false)
  else if (view !== 'home') setView('home')
  else void CapacitorApp.exitApp()
 })
 useEffect(()=>localStorage.setItem('hs-providers',JSON.stringify(providers)),[providers]);useEffect(()=>localStorage.setItem('hs-bookings',JSON.stringify(bookings)),[bookings]);useEffect(()=>localStorage.setItem('hs-reviews',JSON.stringify(reviews)),[reviews]);useEffect(()=>{if(toast){const timer=setTimeout(()=>setToast(''),3200);return()=>clearTimeout(timer)}},[toast])
 const filteredProviders=useMemo(()=>{let results=providers.filter(provider=>{const searchable=`${provider.name} ${provider.role} ${provider.category} ${provider.location} ${provider.services.join(' ')}`.toLowerCase();return(category==='All services'||provider.category===category)&&(!query||searchable.includes(query.toLowerCase()))&&provider.price<=maxPrice&&Number(provider.rating||0)>=minRating&&provider.available!==false});if(sort==='Top rated')results=[...results].sort((a,b)=>b.rating-a.rating);if(sort==='Price: low to high')results=[...results].sort((a,b)=>a.price-b.price);return results},[providers,category,query,maxPrice,minRating,sort])
 const go=target=>{setView(target);setMenuOpen(false);setSelected(null);window.scrollTo({top:0,behavior:'smooth'})},notify=message=>setToast(message)
 function openBooking(provider){setBookingProvider(provider);setBookingStage('details');setDate('2026-10-10');setTime('10:00 AM')}
 function confirmBooking(){const booking={id:`HS-${Math.floor(2100+Math.random()*7000)}`,providerId:bookingProvider.id,providerName:bookingProvider.name,service:bookingProvider.services[0],date,time,address,price:Number(bookingProvider.price),status:'Confirmed',createdAt:new Date().toISOString().slice(0,10),paymentMethod};setBookings(items=>[booking,...items]);setBookingStage('success');setTimeout(()=>{setBookingProvider(null);setView('bookings');window.scrollTo({top:0,behavior:'smooth'});notify('Your booking is confirmed. We’ve sent the details to your account.')},1200)}
 function updateBooking(id,changes){setBookings(items=>items.map(booking=>booking.id===id?{...booking,...changes}:booking))}
 function saveProvider(event){event.preventDefault();if(!form.name.trim()||!form.role.trim()||!form.price)return notify('Add a name, service role and starting price.');const initials=form.name.split(' ').map(word=>word[0]).slice(0,2).join('').toUpperCase();if(manageProvider&&manageProvider!=='new')setProviders(items=>items.map(provider=>provider.id===manageProvider.id?{...provider,...form,price:Number(form.price),initials,services:[form.role]}:provider));else setProviders(items=>[{id:`p-${Date.now()}`,...form,price:Number(form.price),rating:5,reviews:0,experience:'New on HomeService',distance:'Nearby',owner:'provider',initials,color:'peach',verified:false,available:true,services:[form.role]},...items]);setManageProvider(null);setForm(makeProviderForm());notify(manageProvider&&manageProvider!=='new'?'Service listing updated.':'Your new service listing is live.')}
 function editProvider(provider){setManageProvider(provider);setForm({name:provider.name,role:provider.role,category:provider.category,price:provider.price,location:provider.location,description:provider.description});setView('providerDashboard');window.scrollTo({top:0,behavior:'smooth'})}
 function submitReview(event){event.preventDefault();if(!reviewText.trim())return notify('Write a short comment before submitting your review.');setReviews(items=>[{id:`r-${Date.now()}`,bookingId:reviewBooking.id,providerId:reviewBooking.providerId,providerName:reviewBooking.providerName,stars:rating,text:reviewText.trim(),date:new Date().toISOString().slice(0,10)},...items]);setReviewBooking(null);setReviewText('');setRating(5);notify('Thanks for sharing your experience.')}
 const header=<><div className="announcement"><Sparkles/> Reliable home services, right around the corner · Now serving Colombo</div><header className="topbar"><button className="brand" onClick={()=>go('home')}><span className="brand-mark"><Home/></span><span>home<span className="brand-accent">service</span><small>TRUSTED HELP, RIGHT AT HOME</small></span></button><nav className="desktop-nav"><button className={view==='home'?'active':''} onClick={()=>go('home')}>Explore</button><button className={view==='bookings'?'active':''} onClick={()=>go('bookings')}>My bookings</button><button onClick={()=>go('help')}>Help & support</button></nav><div className="top-actions"><button className="icon-button" onClick={()=>notify('You’re all caught up on notifications.')} aria-label="Notifications"><Bell/><i className="notification-dot"/></button><span className="top-divider"/><button className="user-menu" onClick={()=>go('profile')}><span className="tiny-avatar">AP</span><span>Amaya P.</span><ChevronDown/></button><button className="icon-button mobile-menu-button" onClick={()=>setMenuOpen(!menuOpen)}><Menu/></button></div></header>{menuOpen&&<div className="mobile-menu"><button onClick={()=>go('home')}>Explore</button><button onClick={()=>go('bookings')}>My bookings</button><button onClick={()=>go('profile')}>My profile</button><button onClick={()=>go('help')}>Help & support</button></div>}<div className="role-strip"><div className="role-inner"><span>VIEW AS</span>{[['customer','Customer'],['provider','Service provider'],['admin','Admin']].map(([key,label])=><button className={role===key?'selected':''} key={key} onClick={()=>{setRole(key);go(key==='provider'?'providerDashboard':key==='admin'?'admin':'home')}}>{label}</button>)}</div><span className="demo-hint">Demo mode · Switch role to explore each workspace</span></div></>
 return <div className="app-shell">{header}<main className="main-content">{view==='home'&&<HomeView providers={filteredProviders} selectedCategory={category} setCategory={setCategory} query={query} setQuery={setQuery} onFind={()=>go('search')} onSelect={setSelected} onBook={openBooking} bookings={bookings} go={go}/ >}{view==='search'&&<SearchView providers={filteredProviders} category={category} setCategory={setCategory} query={query} setQuery={setQuery} sort={sort} setSort={setSort} onFilter={()=>setFilterOpen(true)} onSelect={setSelected} onBook={openBooking} onClear={()=>{setCategory('All services');setQuery('');setMaxPrice(5000);setMinRating(0)}}/>}{view==='bookings'&&<BookingsView bookings={bookings} activeTab={activeTab} setActiveTab={setActiveTab} onSelect={booking=>setSelected({type:'booking',...booking})} onCancel={id=>{updateBooking(id,{status:'Cancelled'});notify('Booking cancelled. Your provider has been notified.')}} onDelete={id=>{setBookings(items=>items.filter(booking=>booking.id!==id));notify('Booking removed from your list.')}} onReview={setReviewBooking} reviews={reviews} go={go}/ >}{view==='profile'&&<ProfileView profileName={profileName} setProfileName={setProfileName} profileLocation={profileLocation} setProfileLocation={setProfileLocation} bookings={bookings} onSave={()=>notify('Your profile has been saved.')} onEditLocation={()=>notify('Location updated to your saved address.')} go={go}/ >}{view==='providerDashboard'&&<ProviderDashboard providers={providers} bookings={bookings} form={form} setForm={setForm} editing={manageProvider} onSubmit={saveProvider} onEdit={editProvider} onDelete={id=>{setProviders(items=>items.filter(provider=>provider.id!==id));notify('Service listing removed.')}} onAdd={()=>{setManageProvider('new');setForm(makeProviderForm())}} onBookingAction={(id,status)=>{updateBooking(id,{status});notify(`Booking marked ${status.toLowerCase()}.`)}}/>}{view==='admin'&&<AdminView providers={providers} bookings={bookings} onVerify={id=>{setProviders(items=>items.map(provider=>provider.id===id?{...provider,verified:true}:provider));notify('Provider verification approved.')}} onProviderDelete={id=>{setProviders(items=>items.filter(provider=>provider.id!==id));notify('Service listing removed.')}} onBookingAction={(id,status)=>{updateBooking(id,{status});notify(`Booking marked ${status.toLowerCase()}.`)}}/>}{view==='help'&&<HelpView go={go} onContact={()=>notify('Thanks! Support will reply within one working day.')}/ >}{view==='feedback'&&<FeedbackView onSubmit={()=>{notify('Thanks for helping us improve HomeService.');go('home')}}/>}<footer className="footer"><span>© 2026 HomeService · WE_33</span><span>Made for homes in Colombo <b>♥</b></span><button onClick={()=>go('admin')}>Team demo</button></footer></main>
 {selected&&(selected.type==='booking'?<Modal title="Booking details" onClose={()=>setSelected(null)}><BookingDetails booking={selected} onCancel={()=>{updateBooking(selected.id,{status:'Cancelled'});notify('Booking cancelled.');setSelected(null)}} onReview={()=>{setReviewBooking(selected);setSelected(null)}}/></Modal>:<Modal title="Service provider" onClose={()=>setSelected(null)} wide><ProviderDetails provider={selected} reviews={reviews.filter(review=>review.providerId===selected.id)} onBook={()=>{setSelected(null);openBooking(selected)}}/></Modal>)}{bookingProvider&&<Modal title={bookingStage==='success'?'Booking confirmed':bookingStage==='payment'?'Choose payment':'Book this service'} onClose={()=>setBookingProvider(null)}><BookingFlow provider={bookingProvider} stage={bookingStage} setStage={setBookingStage} date={date} setDate={setDate} time={time} setTime={setTime} address={address} setAddress={setAddress} method={paymentMethod} setMethod={setPaymentMethod} onConfirm={confirmBooking}/></Modal>}{filterOpen&&<Modal title="Filter your search" onClose={()=>setFilterOpen(false)}><FilterPanel maxPrice={maxPrice} setMaxPrice={setMaxPrice} minRating={minRating} setMinRating={setMinRating} onApply={()=>setFilterOpen(false)} onReset={()=>{setMaxPrice(5000);setMinRating(0)}}/></Modal>}{manageProvider==='new'&&<Modal title="Add a service listing" onClose={()=>{setManageProvider(null);setForm(makeProviderForm())}}><ProviderForm form={form} setForm={setForm} onSubmit={saveProvider} onCancel={()=>{setManageProvider(null);setForm(makeProviderForm())}}/></Modal>}{reviewBooking&&<Modal title="Rate your experience" onClose={()=>setReviewBooking(null)}><ReviewForm booking={reviewBooking} rating={rating} setRating={setRating} text={reviewText} setText={setReviewText} onSubmit={submitReview}/></Modal>}{toast&&<div className="toast" role="status"><CheckCircle2/>{toast}<button onClick={()=>setToast('')}><X/></button></div>}<BottomNav view={view} go={go}/></div>
}
function BottomNav({view,go}){return <nav className="bottom-nav"><button className={['home','search'].includes(view)?'active':''} onClick={()=>go('home')}><Home/><span>Explore</span></button><button className={view==='search'?'active':''} onClick={()=>go('search')}><Search/><span>Search</span></button><button className={view==='bookings'?'active':''} onClick={()=>go('bookings')}><CalendarDays/><span>Bookings</span></button><button className={view==='profile'?'active':''} onClick={()=>go('profile')}><UserRound/><span>Profile</span></button></nav>}
