-- Member 2 customer preferences, safe payment metadata and feedback.
create table if not exists public.customer_addresses (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, label text not null, address_line text not null, is_default boolean not null default false, created_at timestamptz not null default now());
create table if not exists public.customer_payment_methods (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, method_type text not null check (method_type in ('cash','card','mobile')), label text not null, last_four text, is_default boolean not null default false, created_at timestamptz not null default now());
create table if not exists public.customer_feedback (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, category text not null, message text not null check (char_length(trim(message)) between 10 and 2000), status text not null default 'submitted' check (status in ('submitted','reviewed','resolved')), created_at timestamptz not null default now());
alter table public.customer_addresses enable row level security; alter table public.customer_payment_methods enable row level security; alter table public.customer_feedback enable row level security;
grant select, insert, update, delete on public.customer_addresses, public.customer_payment_methods to authenticated; grant select, insert on public.customer_feedback to authenticated;
create policy customer_addresses_owner on public.customer_addresses for all to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy customer_payment_methods_owner on public.customer_payment_methods for all to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy customer_feedback_read on public.customer_feedback for select to authenticated using (user_id = (select auth.uid()) or (select public.is_admin()));
create policy customer_feedback_insert on public.customer_feedback for insert to authenticated with check (user_id = (select auth.uid()));
